#!/bin/bash
# Build the MAMBA agent env, and the step envs the reference build's transforms ask for.
#
# Under Runtime.MAMBA `Agent.container` is read as a conda ENVIRONMENT NAME, and each
# step resolves its own env the same way -- an `env::*.env` declaration's `conda:` key
# names an environment that must already exist on the host. Nothing creates these on
# demand, so a run that reaches a step whose env is absent dies at that step. This
# script makes all of them up front.
#
# Two things about the agent env that a plain `mamba env create` does not give you:
#
#   1. `src/metasmith/envs/base.yml` is metasmith's DEPENDENCY env. It carries a
#      standing comment that it can hold no pip dependencies, so it never installs
#      metasmith itself -- no `metasmith` console script. The MAMBA launcher runs
#      `mamba run -n <env> metasmith api ...`, so every step's bootstrap would die on
#      `metasmith: not found`. We install shims rather than `pip install -e`, which
#      would write *.egg-info into the pinned submodule and dirty a worktree.
#
#   2. The engine has to be the PINNED one in src/metasmith. A `metasmith` resolved off
#      a global PYTHONPATH (e.g. ~/lib/locals) may point at a different worktree; an
#      activation hook is what wins, because PYTHONPATH is placed ahead of site-packages
#      and a .pth cannot outrank it.
#
# Idempotent: re-run it after `git pull` to repoint the hook and refresh the shims.
set -euo pipefail

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
REPO="$(dirname "$HERE")"
ENGINE="$REPO/src/metasmith/src"

AGENT_ENV="msm-fabfos"

# The step envs. Each name must match the `conda:` key of the matching
# src/metasmith_libraries/resources/env/<tool>.env, or the step will not find it.
STEP_ENVS=(
    "python_for_data_science"
    "ncbi-datasets"
    "build-refs-equilibrator"
    "polars"
)

if command -v mamba >/dev/null 2>&1; then M=mamba; else M=conda; fi
have_env() { $M env list | awk '{print $1}' | grep -qx "$1"; }

echo "== repo:   $REPO"
echo "== engine: $ENGINE"
[ -d "$ENGINE/metasmith" ] || { echo "!! pinned engine missing -- git submodule update --init"; exit 1; }

# ---------------------------------------------------------------- agent env
if have_env "$AGENT_ENV"; then
    echo "== $AGENT_ENV exists, leaving packages alone"
else
    echo "== creating $AGENT_ENV from the engine's base.yml"
    $M env create -n "$AGENT_ENV" -f "$REPO/src/metasmith/envs/base.yml"
fi

PREFIX="$($M run -n "$AGENT_ENV" python -c 'import sys, pathlib; print(pathlib.Path(sys.prefix))' 2>/dev/null | tail -1)"
[ -n "$PREFIX" ] || { echo "!! could not resolve $AGENT_ENV prefix"; exit 1; }

echo "== pinning the engine via an activation hook"
mkdir -p "$PREFIX/etc/conda/activate.d"
cat > "$PREFIX/etc/conda/activate.d/msm_pinned.sh" <<EOF
# generated by envs/setup_agent_env.sh -- points this env at the pinned engine
export PYTHONPATH="$ENGINE\${PYTHONPATH:+:\$PYTHONPATH}"
EOF

echo "== installing console-script shims (metasmith, msm)"
for name in metasmith msm; do
    cat > "$PREFIX/bin/$name" <<'EOF'
#!/usr/bin/env bash
# shim: base.yml cannot carry pip deps, so there is no console script to install.
# `python -m metasmith` resolves through the activation hook's PYTHONPATH.
exec python -m metasmith "$@"
EOF
    chmod +x "$PREFIX/bin/$name"
done

# ---------------------------------------------------------------- step envs
for e in "${STEP_ENVS[@]}"; do
    yml="$HERE/$e.yml"
    [ -f "$yml" ] || { echo "!! no recipe at $yml"; exit 1; }
    if have_env "$e"; then
        echo "== step env $e exists, skipping"
    else
        echo "== creating step env $e"
        $M env create -n "$e" -f "$yml"
    fi
done

# ---------------------------------------------------------------- verify
echo
echo "== verifying"
ver="$($M run -n "$AGENT_ENV" metasmith --version 2>&1 | tail -1)"
resolved="$($M run -n "$AGENT_ENV" python -c 'import metasmith; print(metasmith.__file__)' 2>&1 | tail -1)"
echo "   metasmith --version : $ver"
echo "   resolves to         : $resolved"
case "$resolved" in
    "$ENGINE"/*) echo "   engine              : PINNED (ok)";;
    *)           echo "   engine              : !! NOT the pinned tree"; exit 1;;
esac
$M run -n "$AGENT_ENV" python -c 'from metasmith.python_api import Runtime; assert "MAMBA" in Runtime.__members__, Runtime.__members__; print("   Runtime.MAMBA       : present")'
for e in "${STEP_ENVS[@]}"; do
    have_env "$e" && echo "   step env $e: ok"
done
echo
echo "ready: $AGENT_ENV + ${#STEP_ENVS[@]} step env(s)"
